package com.ishanvohra.sphinx.interfaces

import com.ishanvohra.sphinx.models.completeText.CompleteTextRequest
import com.ishanvohra.sphinx.models.completeText.CompleteTextResult
import com.ishanvohra.sphinx.models.editText.EditTextRequest
import com.ishanvohra.sphinx.models.editText.EditTextResult
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.Header
import retrofit2.http.POST

interface Api {

    /**
     * Complete text API call
     * @param body: Request body for the API call
     * @return Prompts generated by GPT
     * @see CompleteTextResult
     * @see CompleteTextResult
     */
    @POST("completions")
    suspend fun completeText(
        @Header("Authorization") token: String,
        @Body body: CompleteTextRequest
    ): Response<CompleteTextResult>

    /**
     * Edit text API call
     * @param token "Bearer $api_key"
     * @param body request body for the API call
     * @see EditTextRequest
     * @see EditTextResult
     */
    @POST("edits")
    suspend fun editText(
        @Header("Authorization") token: String,
        @Body body: EditTextRequest
    ): Response<EditTextResult>

}