package com.ishanvohra.sphinx

import com.ishanvohra.sphinx.apis.EditText
import com.ishanvohra.sphinx.apis.TextComplete
import com.ishanvohra.sphinx.interfaces.EditTextListener
import com.ishanvohra.sphinx.interfaces.TextCompleteListener
import com.ishanvohra.sphinx.models.completeText.CompleteTextRequest
import com.ishanvohra.sphinx.models.editText.EditTextRequest

class Sphinx(
    private val apiKey: String
) {

    companion object{
        fun getInstance(apiKey: String) = Sphinx(apiKey)
    }

    /**
     * Creates a completion for the provided prompt and parameters
     * @param request
     * @return the response generated by GPT-3
     * @see CompleteTextRequest
     */
    fun completeText(
        listener: TextCompleteListener,
        request: CompleteTextRequest
    ) = TextComplete.getInstance(listener, apiKey).completeText(
        request
    )

    /**
     * Creates a new edit for the provided input, instruction, and parameters.
     * @param request
     * @return the response generated by GPT-3
     * @see EditTextRequest
     */
    fun editText(
        listener: EditTextListener,
        request: EditTextRequest
    ) = EditText.getInstance(listener, apiKey).editText(
        request
    )

}