package com.ishanvohra.sphinx.apis

import com.google.gson.Gson
import com.ishanvohra.sphinx.interfaces.GetModelsListener
import com.ishanvohra.sphinx.models.error.ErrorBody
import com.ishanvohra.sphinx.networking.RetrofitClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class GetModels(
    private val listener: GetModelsListener,
    apiKey: String
) {

    companion object{
        fun getInstance(listener: GetModelsListener, apiKey: String) = GetModels(
            listener,
            apiKey
        )
    }

    private val token = "Bearer $apiKey"
    private val apiClient = RetrofitClient().instance

    /**
     * Gets the list of all models available
     * @return the response generated by GPT-3
     * @see
     */
    fun getModels(){
        CoroutineScope(Dispatchers.Default).launch {
            apiClient.getModels(token).run {
                if(this.isSuccessful && this.body() != null){
                    listener.onSuccess(this.body()!!)
                }
                else{
                    val errorBody = Gson().fromJson(
                        this.errorBody()?.string(),
                        ErrorBody::class.java
                    )
                    listener.onFailure(errorBody)
                }
            }
        }
    }

}