package com.ishanvohra.sphinx.apis

import com.google.gson.Gson
import com.ishanvohra.sphinx.interfaces.TextCompleteListener
import com.ishanvohra.sphinx.models.completeText.CompleteTextRequest
import com.ishanvohra.sphinx.models.error.ErrorBody
import com.ishanvohra.sphinx.networking.RetrofitClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class TextComplete(
    private val listener: TextCompleteListener,
    apiKey: String
){

    companion object {
        fun getInstance(listener: TextCompleteListener, apiKey: String) = TextComplete(
            listener,
            apiKey
        )
    }

    private val token = "Bearer $apiKey"
    private val apiClient = RetrofitClient().instance

    /**
     * Creates a completion for the provided prompt and parameters
     * @param request
     * @return the response generated by GPT-3
     * @see CompleteTextRequest
     */
    fun completeText(request: CompleteTextRequest){
        CoroutineScope(Dispatchers.Default).launch {
            apiClient.completeText(token, request).run {
                if(this.isSuccessful && this.body() != null){
                    listener.onSuccess(this.body()!!)
                }
                else{
                    val errorBody = Gson().fromJson(
                        this.errorBody()?.string(),
                        ErrorBody::class.java
                    )
                    listener.onFailure(errorBody)
                }
            }
        }
    }

}